// Generated by omlx/admin/build_tokens.py from omlx/admin/tokens.json.
// Do not edit by hand: edit tokens.json and rerun the script.
//
// Numeric tokens the web console and the app share. Surfaces, text and
// control colors stay with OMLXTheme, which resolves them through AppKit
// dynamic system colors so the app keeps tracking System Settings.

import CoreGraphics

enum DesignTokens {
    /// 8pt layout grid; `x1` is the 4pt icon-to-label gap.
    enum Space {
        static let x1: CGFloat = 4
        static let x2: CGFloat = 8
        static let x3: CGFloat = 12
        static let x4: CGFloat = 16
        static let x5: CGFloat = 24
        static let x6: CGFloat = 32
        static let x8: CGFloat = 48
        static let x10: CGFloat = 64
    }

    enum Radius {
        static let sm: CGFloat = 6
        static let md: CGFloat = 8
        static let lg: CGFloat = 12
        static let pill: CGFloat = 999
    }

    /// The six type levels, in points.
    enum FontSize {
        static let aux: CGFloat = 10
        static let body: CGFloat = 12
        static let emphasis: CGFloat = 15
        static let section: CGFloat = 17
        static let page: CGFloat = 20
        static let kpi: CGFloat = 28

        /// Smallest size any auxiliary label may use.
        static let floor: CGFloat = 10
        /// Smallest size body copy and above may use.
        static let bodyFloor: CGFloat = 12
        /// Floor once enhanced readability is on.
        static let enhancedReadabilityFloor: CGFloat = 12
    }

    enum LineHeight {
        static let aux: CGFloat = 1.4
        static let body: CGFloat = 1.5
        static let emphasis: CGFloat = 1.45
        static let section: CGFloat = 1.4
        static let page: CGFloat = 1.3
        static let kpi: CGFloat = 1.15
    }

    enum Container {
        static let gutter: CGFloat = 32
        static let form: CGFloat = 760
        static let wide: CGFloat = 1200
    }

    enum Material {
        static let topBarBlur: CGFloat = 20
        static let topBarSaturate: CGFloat = 1.8
    }
}
